- name: myplaybook
  hosts: all
  remote_user: mostafa
  gather_facts: false

  tasks:
  - name: Copy index file
    copy: 
      src: ./src
      dest: /home/mostafa/
    tags: copy
  - name: run simple app
    ansible.builtin.command: python3 src/app.py
      
    